services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-website
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/db/custom.db
    volumes:
      - ./db:/app/db
